name: docs-release-action
description: Build & Upload Docs & Release

inputs:
  revision:
    required: true
  src-root:
    required: true
    default: "./"
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  lint-root:
    default: "./_docs-lint"
  build-root:
    default: "./_docs-build"

runs:
  using: composite
  steps:
    - name: Build
      uses: diplodoc-platform/docs-build-action@v1
      with:
        src-root: ${{ inputs.src-root }}
        revision: ${{ inputs.revision }}
        storage-bucket: ${{ inputs.storage-bucket }}
        storage-endpoint: ${{ inputs.storage-endpoint }}
        storage-access-key-id: ${{ inputs.storage-access-key-id }}
        storage-secret-access-key: ${{ inputs.storage-secret-access-key }}
        storage-region: ${{ inputs.storage-region }}
        lint-root: ${{ inputs.lint-root }}
        build-root: ${{ inputs.build-root }}
    - name: Create head folder
      shell: bash
      run: mkdir -p head
    - name: Write revision to head file
      shell: bash
      run: |
        echo "{ \"revision\": \"${{ inputs.revision }}\" }" > head/head
    - name: Upload head file to storage
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --content-type=application/json
      env:
        SOURCE_DIR: "head"
        AWS_S3_BUCKET: ${{ inputs.storage-bucket }}
        AWS_S3_ENDPOINT: ${{ inputs.storage-endpoint }}
        AWS_ACCESS_KEY_ID: ${{ inputs.storage-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.storage-secret-access-key }}
        AWS_REGION: ${{ inputs.storage-region }}
